[web]
web-server ansible_host=44.251.110.237

[app]
app-server ansible_host=35.95.136.230

[db]
db-server ansible_host=54.244.68.94

[all:vars]
ansible_user=ec2-user
ansible_ssh_private_key_file=~/.ssh/ansible-practice
ansible_python_interpreter=/usr/bin/python3

[application:children]
web
app

[all_servers:children]
application
db
